
SECTION "Item Icons 1", ROMX

ItemIcons1::
NoItemIcon::					INCBIN "gfx/overworld/noitem.2bpp"
MasterBallIcon::   				
UltraBallIcon::    				
BrightPowderIcon::
GreatBallIcon::    				
PokeBallIcon::     				INCBIN "gfx/sprites/poke_ball.2bpp"
TownMapIcon::                   INCBIN "gfx/overworld/noitem.2bpp"
BicycleIcon::      				
MoonStoneIcon::
AntidoteIcon::
BurnHealIcon::
IceHealIcon::
AwakeningIcon::
ParlyzHealIcon::
FullRestoreIcon::
MaxPotionIcon::
HyperPotionIcon::
SuperPotionIcon::
PotionIcon::					INCBIN "gfx/itemicons/potion.2bpp"
EscapeRopeIcon::				INCBIN "gfx/overworld/noitem.2bpp"
RepelIcon::
MaxElixirIcon::
FireStoneIcon::   				
ThunderStoneIcon::
WaterStoneIcon::
Item19Icon::
HPUpIcon::         				
ProteinIcon::
IronIcon::
CarbosIcon::
LuckyPunchIcon::
CalciumIcon::		
RareCandyIcon::
XAccuracyIcon::
LeafStoneIcon::
MetalPowderIcon::
NuggetIcon::
PokeDollIcon::
FullHealIcon::     				
ReviveIcon::
MaxReviveIcon::
GuardSpecIcon::
SuperRepelIcon::
MaxRepelIcon::
DireHitIcon::
Item2dIcon::
FreshWaterIcon::
SodaPopIcon::      				
LemonadeIcon::     				
XAttackIcon::
Item32Icon::
XDefendIcon::
XSpeedIcon::
XSpecialIcon::
CoinCaseIcon::
ItemfinderIcon::
PokeFluteIcon::
ExpShareIcon::
OldRodIcon::       				
GoodRodIcon::
SilverLeafIcon::				
SuperRodIcon::     			
PPUpIcon::
EtherIcon::
MaxEtherIcon::
ElixirIcon::
RedScaleIcon::
SecretPotionIcon::
SSTicketIcon::
MysteryEggIcon::
ClearBellIcon::
SilverWingIcon::
MoomooMilkIcon::
QuickClawIcon::
PsnCureBerryIcon::
GoldLeafIcon::
SoftSandIcon::
SharpBeakIcon::
PrzCureBerryIcon::
BurntBerryIcon::
IceBerryIcon::
PoisonBarbIcon::
KingsRockIcon::
BitterBerryIcon::
MintBerryIcon::
RedApricornIcon::
TinyMushroomIcon::
BigMushroomIcon::
SilverPowderIcon::
BluApricornIcon::
Item5aIcon::
AmuletCoinIcon::
YlwApricornIcon::
GrnApricornIcon::
CleanseTagIcon::
MysticWaterIcon::
TwistedSpoonIcon::
WhtApricornIcon::
BlackBelIIcon::
BlkApricornIcon::
Item64Icon::
PnkApricornIcon::
BlackGlassesIcon::
SlowpokeTailIcon::
PinkBowIcon::
StickIcon::
SmokeBallIcon::
NeverMeltIceIcon::
MagnetIcon::
MiracleBerryIcon::
PearlIcon::
BigPearlIcon::
EverstoneIcon::
SpellTagIcon::
RageCandyBarIcon::
GSBallIcon::
BlueCardIcon::
MiracleSeedIcon::
ThickClubIcon::
FocusBandIcon::
Item78Icon::
EnergyPowderIcon::
EnergyRootIcon::
HealPowderIcon::
RevivalHerbIcon::
HardStoneIcon::
LuckyEggIcon::
CardKeyIcon::
MachinePartIcon::
EggTicketIcon::
LostItemIcon::
StardustIcon::
StarPieceIcon::
BasementKeyIcon::
PassIcon::
Item87Icon::
Item88Icon::
Item89Icon::
CharcoalIcon::
BerryJuiceIcon::
ScopeLensIcon::
Item8dIcon::
Item8eIcon::
MetalCoatIcon::
DragonFangIcon::
Item91Icon::
LeftoversIcon::
Item93Icon::
Item94Icon::
Item95Icon::
MysteryBerryIcon::
DragonScaleIcon::
BerserkGeneIcon::
Item99Icon::
Item9aIcon::
Item9bIcon::
SacredAshIcon::
HeavyBallIcon::
FlowerMailIcon::
LevelBallIcon::
LureBallIcon::
FastBallIcon::
ItemA2Icon::
LightBallIcon::
FriendBallIcon::
MoonBallIcon::
LoveBallIcon::
NormalBoxIcon::
GorgeousBoxIcon::
SunStoneIcon::
PolkadotBowIcon::
ItemAbIcon::
UpGradeIcon::
BerryIcon::
GoldBerryIcon::
SquirtBottleIcon::
ItemB0Icon::
ParkBallIcon::
RainbowWingIcon::
ItemB3Icon::
BrickPieceIcon::
SurfMailIcon::					INCBIN "gfx/overworld/noitem.2bpp"
LiteBlueMailIcon::
PortraiMailIcon::
LovelyMailIcon::
EonMailIcon::
MorphMailIcon::
BlueSkyMailIcon::
MusicMailIcon::
MirageMailIcon::
ItemBeIcon::
ItemDcIcon::    
ItemC3Icon::     
ItemFaIcon::    

TMHMIcon::         				INCBIN "gfx/overworld/noitem.2bpp"